print("Hola Mundo")
print(type(12))
print(("hola mundo ")+ str(10))
print((("hola mundo ") + str(10 ) + " ") *2)
masa= 75
altura= 1.80
imc= masa/(altura**2)
print (imc)

trabajo=(input) ("Como se llama tu Empresa?")
direccion= (input)("Cual es tu direccion de empleo?")
edad= int(input("Cual es tu edad?"))

print ("Renato trabaje en", trabajo, "que queda en", direccion, "y tiene", edad)


# Solicitar al usuario ingresar un valor entero
valor = int (input("Ingresa un valor entero: "))

# Calcular el cuadrado del valor ingresado
cuadrado_valor = valor**2

# Modifica lo que necesites pero no la salida impresa
print(cuadrado_valor)

SDASDASD